### ISSUE TITLE
Is it possible to include credentials in loadRemote function from @module-federation/enhanced/runtime?

### ISSUE THREAD

**Issue by badiuoanaalexandra** [module-federation/enhanced#15]
Hi!

Thank you so much for the awesome work you have done with module federation! 

I started using @module-federation/enhanced/runtime to load my remotes dynamically using init and loadRemote functions. Everything worked well, however I currently have a situation where I need to load my remote from another server that needs authentication session cookies passed in order to load the files. 

Can I somehow pass something to the loadRemote function to make it include credentials?

Thank you!

**Comment by VanTigranyan** [comment]
Hi. 
Option 1. Put both the host app and remote app server under the same domain, so that when you login in shell app the cookie would apply to the second server too. The simplest way would be to use a reverse proxy or domain alias.
Option 2. Use a service worker that catches these specific requests and attaches whatever you need to the request.
Option 3. Do not use a private server for static files. IMHO it doesn't make sense. Deploy them to S3/Cloudfront. It's much more convenient. Anything that get's loaded in the browser is already exposed anyway. So the UI code, should not be private or should not contain private information by default. If there is something private in the UI, you could make these parts of the UI dynamically rendered after an authorized API request.

I am not one of the maintainers, but at least that's what I would do.

**Comment by badiuoanaalexandra** [comment]
Hi, @VanTigranyan! I am aware of all the options you posted, however this was a special situation with a time constraint. 
In the end we went with a different approach where we don't need to do this anymore (we use a third party like preemptive to obfuscate part of the code while keeping the code public), however I was still curious if this would be possible. I will close this ticket.
